### ISSUE TITLE
TypeError: pipeline() got an unexpected keyword argument 'requirements_file'

### ISSUE THREAD

**Issue by Coder-Vishali** [zenml-io/zenfiles#41]
I was trying to implement "Predicting how a customer will feel about a product before they even ordered it". I face this issue while running the below script:

python run_deployment.py

**Error:**
C:\Users\vsriniva\Desktop\zenml\zenfiles\customer-satisfaction\py_venv\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pand
as in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\vsriniva\Desktop\zenml\zenfiles\customer-satisfaction\run_deployment.py:3 in <module>   │
│                                                                                                  │
│     1 import click                                                                               │
│     2 from materializer.custom_materializer import cs_materializer                               │
│ >   3 from pipelines.deployment_pipeline import (                                                │
│     4 │   DeploymentTriggerConfig,                                                               │
│     5 │   MLFlowDeploymentLoaderStepConfig,                                                      │
│     6 │   continuous_deployment_pipeline,                                                        │
│                                                                                                  │
│ C:\Users\vsriniva\Desktop\zenml\zenfiles\customer-satisfaction\pipelines\deployment_pipeline.py: │
│ 107 in <module>                                                                                  │
│                                                                                                  │
│   104 │   return prediction                                                                      │
│   105                                                                                            │
│   106                                                                                            │
│ > 107 @pipeline(enable_cache=True, requirements_file=requirements_file)                          │
│   108 def continuous_deployment_pipeline(                                                        │
│   109 │   ingest_data,                                                                           │
│   110 │   clean_data,                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: pipeline() got an unexpected keyword argument 'requirements_file'

**Comment by Coder-Vishali** [comment]
The pipeline decorator doesn't have a **requirements_file** parameter any longer and that code might be a bit outdated. Tried replacing it with **requirements** instead. It  worked!
Refer the API docs here: https://apidocs.zenml.io/0.13.0/api_docs/pipelines/#zenml.pipelines.pipeline_decorator

**Comment by dnth** [comment]
Thanks for reporting it here @Coder-Vishali !
