### ISSUE TITLE
ModuleNotFoundError: No module named 'zenml.integrations.mlflow.mlflow_utils'

### ISSUE THREAD

**Issue by Coder-Vishali** [zenml-io/zenfiles#42]
I am trying to implement customer satisfaction using zenml:
While I execute this script: python run_deployment.py, I face below error

zenfiles-main/customer-satisfaction/venv/lib/python3.6/site-packages/zenml/integrations/mlflow/services/mlflow_deployment.py:5: FutureWarning: MLflow support for Python 3.6 is deprecated and will be dropped in an upcoming release. At that point, existing Python 3.6 workflows that use MLflow will continue to work without modification, but Python 3.6 users will no longer get access to the latest MLflow features and bugfixes. We recommend that you upgrade to Python 3.7 or newer.
  from mlflow.pyfunc.backend import PyFuncBackend  # type: ignore [import]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│zenfiles-main/customer-satisfaction/run_deployment.py:18 in <module>       │
│                                                                                                  │
│    15 from steps.evaluation import evaluation                                                    │
│    16 from steps.ingest_data import ingest_data                                                  │
│    17 from steps.model_train import train_model                                                  │
│ ❱  18 from zenml.integrations.mlflow.mlflow_utils import get_tracking_uri                        │
│    19 from zenml.integrations.mlflow.steps import MLFlowDeployerConfig                           │
│    20 from zenml.services import load_last_service_from_step                                     │
│    21 from zenml.integrations.mlflow.steps import mlflow_model_deployer_step                     │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                  __annotations__ = {}                                                        │ │
│ │                     __builtins__ = <module 'builtins' (built-in)>                            │ │
│ │                       __cached__ = None                                                      │ │
│ │                          __doc__ = None                                                      │ │
│ │                         __file__ = 'run_deployment.py'                                       │ │
│ │                       __loader__ = <_frozen_importlib_external.SourceFileLoader object at    │ │
│ │                                    0x7f900afdc1d0>                                           │ │
│ │                         __name__ = '__main__'                                                │ │
│ │                      __package__ = None                                                      │ │
│ │                         __spec__ = None                                                      │ │
│ │                       clean_data = <class 'steps.clean_data.clean_data'>                     │ │
│ │                            click = <module 'click' from                                      │ │
│ │                                    '/home/laiml/Downloads/zenfiles-main/customer-satisfacti… │ │
│ │   continuous_deployment_pipeline = <class                                                    │ │
│ │                                    'zenml.pipelines.base_pipeline.continuous_deployment_pip… │ │
│ │                  cs_materializer = <class                                                    │ │
│ │                                    'materializer.custom_materializer.cs_materializer'>       │ │
│ │               deployment_trigger = <class                                                    │ │
│ │                                    'pipelines.deployment_pipeline.deployment_trigger'>       │ │
│ │          DeploymentTriggerConfig = <class                                                    │ │
│ │                                    'pipelines.deployment_pipeline.DeploymentTriggerConfig'>  │ │
│ │                 dynamic_importer = <class 'pipelines.deployment_pipeline.dynamic_importer'>  │ │
│ │                       evaluation = <class 'steps.evaluation.evaluation'>                     │ │
│ │               inference_pipeline = <class                                                    │ │
│ │                                    'zenml.pipelines.base_pipeline.inference_pipeline'>       │ │
│ │                      ingest_data = <class 'steps.ingest_data.ingest_data'>                   │ │
│ │ MLFlowDeploymentLoaderStepConfig = <class                                                    │ │
│ │                                    'pipelines.deployment_pipeline.MLFlowDeploymentLoaderSte… │ │
│ │        prediction_service_loader = <class                                                    │ │
│ │                                    'pipelines.deployment_pipeline.prediction_service_loader… │ │
│ │                        predictor = <class 'pipelines.deployment_pipeline.predictor'>         │ │
│ │                            print = <function print at 0x7f8f98e2bd08>                        │ │
│ │                      train_model = <class 'steps.model_train.train_model'>                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'zenml.integrations.mlflow.mlflow_utils'

**Comment by dnth** [comment]
Hi @Coder-Vishali, which version of zenml are you running on? This zenfile was built using `zenml==0.10.0`. So it may be best if you could install the same version to run this. :)

**Comment by Coder-Vishali** [comment]
When I try to install that particular version, it says no matching distribution:

**pip install zenml==0.10.0**
ERROR: Could not find a version that satisfies the requirement zenml==0.10.0 (from versions: 0.0.1rc1, 0.0.1rc2, 0.1.0, 0.1.1, 0.1.2, 0.1.3rc0, 0.1.3, 0.1.4, 0.1.5, 0.2.0rc1, 0.2.0rc2, 0.2.0, 0.3.1rc0, 0.3.1, 0.3.2, 0.3.3rc0, 0.3.3, 0.3.4rc0, 0.3.4, 0.3.5rc0, 0.3.5, 0.3.6rc0, 0.3.6, 0.3.6.1, 0.3.7rc0, 0.3.7, 0.3.7.1rc0, 0.3.7.1rc1, 0.3.7.1rc3, 0.3.7.1rc4, 0.3.8, 0.3.9rc1, 0.3.9rc2, 0.5.0rc1, 0.5.0rc2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.6.0, 0.6.1, 0.6.2)
ERROR: No matching distribution found for zenml==0.10.0
 
The version I am using:
**zenml -v**
zenml, version 0.6.2

The Python version which I use is 3.6.9

**Comment by dnth** [comment]
I see.. could you perhaps try 

`pip install --no-cache-dir zenml==0.10.0`?

**Comment by Coder-Vishali** [comment]
**pip install --no-cache-dir zenml==0.10.0**

ERROR: Could not find a version that satisfies the requirement zenml==0.10.0 (from versions: 0.0.1rc1, 0.0.1rc2, 0.1.0, 0.1.1, 0.1.2, 0.1.3rc0, 0.1.3, 0.1.4, 0.1.5, 0.2.0rc1, 0.2.0rc2, 0.2.0, 0.3.1rc0, 0.3.1, 0.3.2, 0.3.3rc0, 0.3.3, 0.3.4rc0, 0.3.4, 0.3.5rc0, 0.3.5, 0.3.6rc0, 0.3.6, 0.3.6.1, 0.3.7rc0, 0.3.7, 0.3.7.1rc0, 0.3.7.1rc1, 0.3.7.1rc3, 0.3.7.1rc4, 0.3.8, 0.3.9rc1, 0.3.9rc2, 0.5.0rc1, 0.5.0rc2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.6.0, 0.6.1, 0.6.2)
ERROR: No matching distribution found for zenml==0.10.0

Still I see the same issue

**Comment by Coder-Vishali** [comment]
I see the problem is with python version. It doesn't support 3.6.9. I have upgrade it and it works

**Comment by Coder-Vishali** [comment]
Actually, it is working with zenml version 0.13.1. The problem was python version needs to be upgraded!

**Comment by dnth** [comment]
I'm glad it worked. Thanks for reporting it here. It may be useful for users to know that ZenML now supports Python 3.7, 3.8 and 3.9.

**Comment by AntoineDps** [comment]
Hi !

I have a similar problem when trying to import enable_mlflow with the following error when importing as 

`from zenml.integrations.mlflow.mlflow_step_decorator import enable_mlflow`:

> ModuleNotFoundError: No module named 'zenml.integrations.mlflow.mlflow_step_decorator'


python: `3.10.16`
zenml: `2.21.0` 
mlflow: `0.75.0`

**Comment by AntoineDps** [comment]
Yes that is correct.
I got some inspired from some older code then I guess, this explains the import error. 
I will try with some more recent implementation, with `experiment_tracker` argument notably.

**Comment by bcdurak** [comment]
Amazing, you can find our most up-to-date docs regarding `mlflow` [right here](https://docs.zenml.io/stacks/experiment-trackers/mlflow). Also, our [end-to-end example](https://github.com/zenml-io/zenml/tree/main/examples/e2e) uses the mlflow integration if you are interested. Keep in mind, we are currently investigating an issue with mlflow `2.21.0`, so I would advise you to use `2.20.0` if possible.
